[package]
name = "gq4x4"
version = "0.1.0"
authors = ["Kevin Clark <kevin.clark@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusb = "0.6"
rustyline = "7"
rustyline-derive = "0.4"
hex-literal = "0.3"
